steps:
  # 步驟 1: 安裝依賴並構建項目
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  # 步驟 2: 構建 Docker 鏡像
  # 使用 BUILD_ID 作為標籤（總是存在，無論是從 Git 還是直接提交）
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/foodsafety-web:${BUILD_ID}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/foodsafety-web:latest'
      - '.'
  
  # 步驟 3: 推送鏡像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/foodsafety-web:${BUILD_ID}']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/foodsafety-web:latest']
  
  # 步驟 4: 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'foodsafety-web'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/foodsafety-web:${BUILD_ID}'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/${PROJECT_ID}/foodsafety-web:${BUILD_ID}'
  - 'gcr.io/${PROJECT_ID}/foodsafety-web:latest'
